image: node:13

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install --progress=false
    - npm run build

production:
  stage: deploy
  dependencies:
    - build
  before_script:
    - apt-get update -qq && apt-get install -y -qq rsync
  script:
    - *init_ssh
    - rsync -rav --delete blog/.vuepress/dist/* guillaumeh@dawndash.ovh:/home/guillaumeh/blog/
#    - ssh guillaumeh@dawndash.ovh 'bash' < ./deploy/restart.sh
  environment:
    name: production
    url: https://blog.dawndash.ovh
  when: manual
  only:
    - master